# Stage 1: Build the application using Maven
FROM maven:3.9.6-eclipse-temurin-17 AS build
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Create a slim runtime image
FROM eclipse-temurin:17-jdk-alpine
COPY --from=build target/chessmaster-0.0.1-SNAPSHOT.jar ChessmasterApplication.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "ChessmasterApplication.jar"]
