spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 122311902394-mi66gcakhtecn8gsuv6ls87icthhk1tj.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "https://chessbackend-production.up.railway.app/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

# app:
#   jwt:
#     secret: my-super-secret-key-that-is-very-long
#     expiration: 3600000 # 1 hour

server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: none

